version: '1'

services:
  expense-tracker:
    container_name: user-crud
    image: user-crud:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mysqldb
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_USER: hft
      DATABASE_PASSWORD: admin
      DATABASE_NAME: userdb
      DATABASE_PORT: 3306
    expose:
      - "8080"

  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdb
      MYSQL_USER: hft
      MYSQL_PASSWORD: admin